version: "3"
services:
  app:
    build: .
    expose:
      - "3000"
    deploy:
      mode: replicated
      replicas: ${APP_INSTANCES:-1}
      resources:
        limits:
          cpus: "${CPU_LIMIT:-0.75}"
          memory: ${MEMORY_LIMIT:-512M}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "${NGINX_CPU_LIMIT:-0.25}"
          memory: ${NGINX_MEMORY_LIMIT:-128M}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
